import { Inter } from 'next/font/google';
import './globals.css';
import Navbar from "../components/Navbar"
import Footer from "../components/Footer"
import { TanstackProvider } from "../providers/TanstackProvider"
import ReduxProvider from "../providers/ReduxProviders"

const inter = Inter({ subsets: ['latin'] });

export const metadata = {
  title: 'Mendadak Event',
  description: 'Generated by Immanuel, Kiki, Bulan',
};


export default function RootLayout({ children, }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ReduxProvider>
          <TanstackProvider>
            <Navbar />
            {children}
            <Footer />
          </TanstackProvider>
        </ReduxProvider>
      </body>
    </html>
  );
}
