import { Inter } from 'next/font/google';


import Sidebar from '@/components/Sidebar';
import OrganizerSidebar from './../../components/OrganizerSidebar'

const inter = Inter({ subsets: ['latin'] });

export const metadata = {
  title: 'Mendadak Event',
  description: 'Generated by Immanuel, Kiki, Bulan',
};


export default function RootOrganizer({ children }) {
  return (
    <OrganizerSidebar>
      {children}
    </OrganizerSidebar>
  );
}
