import { Inter } from 'next/font/google';


import Sidebar from '@/components/Sidebar';
import AdminSidebar from './../../components/AdminSidebar'

const inter = Inter({ subsets: ['latin'] });

export const metadata = {
  title: 'Mendadak Event',
  description: 'Generated by Immanuel, Kiki, Bulan',
};


export default function RootAdmin({ children }) {
  return (
    <AdminSidebar>
      {children}
    </AdminSidebar>
  );
}
